"""Score benchmark outputs against ground-truth markdown.

Reads `results/<fixture>/<tool>/<fixture>.md` and compares to
`fixtures/<fixture>.expected.md`. Emits a summary JSON and (optionally)
updates `doc/benchmarks.md` with a result table.
"""

from __future__ import annotations

import argparse
import json
from difflib import SequenceMatcher
from pathlib import Path

ROOT = Path(__file__).resolve().parent
FIXTURES = ROOT / "fixtures"
RESULTS = ROOT / "results"
DOC = ROOT.parents[2] / "doc" / "benchmarks.md"


def _similarity(actual: str, expected: str) -> float:
    return round(SequenceMatcher(None, actual, expected).ratio(), 3)


def _heading_f1(actual: str, expected: str) -> float:
    a = {line.strip() for line in actual.splitlines() if line.startswith("#")}
    e = {line.strip() for line in expected.splitlines() if line.startswith("#")}
    if not a and not e:
        return 1.0
    if not a or not e:
        return 0.0
    tp = len(a & e)
    if tp == 0:
        return 0.0
    precision = tp / len(a)
    recall = tp / len(e)
    return round(2 * precision * recall / (precision + recall), 3)


def _table_cell_f1(actual: str, expected: str) -> float:
    def cells(s: str) -> set[str]:
        out: set[str] = set()
        for line in s.splitlines():
            if "|" in line and not line.lstrip().startswith("#"):
                out.update(c.strip() for c in line.split("|") if c.strip())
        return out

    a, e = cells(actual), cells(expected)
    if not a and not e:
        return 1.0
    if not a or not e:
        return 0.0
    tp = len(a & e)
    if tp == 0:
        return 0.0
    precision = tp / len(a)
    recall = tp / len(e)
    return round(2 * precision * recall / (precision + recall), 3)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--update-doc", action="store_true", help=f"write summary to {DOC}")
    args = p.parse_args(argv)

    rows: list[dict[str, object]] = []
    for fixture_dir in sorted(d for d in RESULTS.iterdir() if d.is_dir()):
        expected_path = FIXTURES / f"{fixture_dir.name}.expected.md"
        if not expected_path.is_file():
            continue
        expected = expected_path.read_text(encoding="utf-8")
        for tool_dir in sorted(d for d in fixture_dir.iterdir() if d.is_dir()):
            md_path = tool_dir / f"{fixture_dir.name}.md"
            if not md_path.is_file():
                continue
            actual = md_path.read_text(encoding="utf-8")
            result_meta_path = tool_dir / "result.json"
            meta = json.loads(result_meta_path.read_text()) if result_meta_path.is_file() else {}
            rows.append(
                {
                    "fixture": fixture_dir.name,
                    "tool": tool_dir.name,
                    "similarity": _similarity(actual, expected),
                    "heading_f1": _heading_f1(actual, expected),
                    "table_cell_f1": _table_cell_f1(actual, expected),
                    "wall_seconds": meta.get("wall_seconds"),
                }
            )

    print(json.dumps(rows, indent=2))

    if args.update_doc and rows:
        DOC.parent.mkdir(parents=True, exist_ok=True)
        with DOC.open("w", encoding="utf-8") as f:
            f.write("# Benchmarks\n\n")
            f.write("Honest comparison vs. competing OCR/PDF→Markdown tools. ")
            f.write("See [`backend/tests/bench/README.md`](../backend/tests/bench/README.md) for methodology.\n\n")
            f.write("| Fixture | Tool | Similarity | Heading F1 | Table cell F1 | Wall (s) |\n")
            f.write("|---|---|---|---|---|---|\n")
            for r in rows:
                f.write(
                    f"| {r['fixture']} | {r['tool']} | {r['similarity']} | "
                    f"{r['heading_f1']} | {r['table_cell_f1']} | {r['wall_seconds']} |\n"
                )
            f.write("\n_(generated by `tests/bench/score.py --update-doc`)_\n")
        print(f"\nwrote {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
